### ISSUE TITLE
Change concept_id field from Int to String

### ISSUE THREAD

**Issue by mielvds** [OnroerendErfgoed/skosprovider_sqlalchemy#87]
The int datatype prevents URIs to be stored as concept_id's, which causes issues in combination with the `skosprovider_rdf`. See #74

**Comment by koenedaele** [comment]
Todo:

- Change concept_id from int to string
- Document change in README as a BC braking change. Clients with an existing database will need to upgrade their database by writing a script or doing some SQL work. It looks like the lib is mostly only used in Atramhasis and we will provide an upgrade there, so maybe nobody will actually be bothered by this change
- Bump version from 1.0.0 to 2.0.0 to signal this BC change.
